### ISSUE TITLE
bosh clean-up --all failed with tls handshake

### ISSUE THREAD

**Issue by alex-slynko** [cloudfoundry-incubator/bosh-google-cpi-release#205] opened 2017-07-06 12:59 UTC
we are using BOSH 262 & CPI 25.9.0 in our CI. We have 7 bosh workers.

We were running clean-up after all tests and got the following error:
```
12:34:03 | Deleting orphaned disks: disk-e6936ef4-5970-4191-6577-67691527e16b (00:00:10)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting disk 'disk-e6936ef4-5970-4191-6577-67691527e16b': Failed to find Google Disk 'disk-e6936ef4-5970-4191-6577-67691527e16b': Get https://www.googleapis.com/compute/v1/projects/cf-pcf-kubo/aggregated/disks?alt=json&filter=name+eq+.%2Adisk-e6936ef4-5970-4191-6577-67691527e16b: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout' in 'delete_disk' CPI method
12:34:04 | Deleting orphaned disks: disk-88091301-4e77-4678-4b8f-e8585af7a597 (00:00:10)
            L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting disk 'disk-88091301-4e77-4678-4b8f-e8585af7a597': Failed to find Google Disk 'disk-88091301-4e77-4678-4b8f-e8585af7a597': Get https://www.googleapis.com/compute/v1/projects/cf-pcf-kubo/aggregated/disks?alt=json&filter=name+eq+.%2Adisk-88091301-4e77-4678-4b8f-e8585af7a597: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout' in 'delete_disk' CPI method

12:34:04 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'Deleting disk 'disk-e6936ef4-5970-4191-6577-67691527e16b': Failed to find Google Disk 'disk-e6936ef4-5970-4191-6577-67691527e16b': Get https://www.googleapis.com/compute/v1/projects/cf-pcf-kubo/aggregated/disks?alt=json&filter=name+eq+.%2Adisk-e6936ef4-5970-4191-6577-67691527e16b: oauth2: cannot fetch token: Post https://accounts.google.com/o/oauth2/token: net/http: TLS handshake timeout' in 'delete_disk' CPI method
```

The job was deleting multiple disks, but failed to delete 3 disks.
The problems like this happen pretty often in our environment. Is there a way to increase log level so we can provide more information for you?

**Comment by dpb587-pivotal** [comment] 2017-07-12 19:16
I think this is a duplicate of #203.

**Comment by johnsonj** [comment] 2017-07-13 18:27
Agreed this is a dup, closing to track retries on the older bug

**Closed by johnsonj** 2017-07-13 18:27 UTC
